# Generated by Django 5.2.7 on 2025-11-03 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vuser',
            new_name='user',
        ),
    ]
