# Generated by Django 5.2.7 on 2025-11-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_vuser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('Organization_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
