# Generated by Django 5.2.7 on 2025-11-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_employee_user_delete_vuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='scan_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email_id', models.EmailField(blank=True, max_length=30, null=True)),
                ('address', models.TextField(blank=True, max_length=100, null=True)),
                ('Phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('office_number', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('company_website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
