# Generated by Django 5.2.7 on 2025-11-14 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_scan_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scan_card',
            old_name='email_id',
            new_name='email',
        ),
    ]
