# Generated by Django 5.2.7 on 2025-11-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_email_id_scan_card_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan_card',
            name='office_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
