# Generated by Django 5.2.7 on 2025-11-14 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_scan_card_office_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule_meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('purpose_of_meeting', models.CharField(blank=True, max_length=100, null=True)),
                ('meeting_type', models.CharField(blank=True, default='Google meet', max_length=100, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Time', models.TimeField(blank=True, null=True)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.scan_card')),
            ],
        ),
    ]
