# Generated by Django 5.2.7 on 2025-11-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_schedule_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule_meeting',
            name='is_accept',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule_meeting',
            name='is_reject',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
