# Generated by Django 5.2.7 on 2025-11-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_schedule_meeting_is_accept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule_meeting',
            name='is_closed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
