# Generated by Django 5.2.7 on 2025-11-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_employee_user_profile_user_profile_eventpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpost',
            name='comments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='eventpost',
            name='like_by',
            field=models.ManyToManyField(blank=True, related_name='like', to='api.user'),
        ),
        migrations.AddField(
            model_name='eventpost',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventpost',
            name='media',
            field=models.FileField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventpost',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='save_post', to='api.user'),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
